name: LudoMania
version: 1.1
main: ru.ludomania.LudoPlugin
api-version: 1.20
folia-supported: true
author: ExpertX_DA
description: Плагин на лудоманию с бочками и ломкой для Folia.

# Регистрация команд обязательна!
commands:
  ludo:
    description: Посмотреть статус своей зависимости (сколько депнул и процент кайфа)
    usage: /ludo
    aliases: [ludostats, dep]